name: Build debian

on:
  push:
  
jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: |
          sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - name: Build
        run: dpkg-buildpackage 